param([string]$Token)

$headers = @{
    Authorization = "token $Token"
    "User-Agent"  = "kiro-issue-updater"
    Accept        = "application/vnd.github.v3+json"
}
$repo = "Hahfyeex/Stellar-PolyMarket"

function Update-Issue([int]$number, [string]$body) {
    $tmp = [System.IO.Path]::GetTempFileName()
    $obj = [PSCustomObject]@{ body = $body }
    $obj | ConvertTo-Json -Depth 2 -Compress | Set-Content -Path $tmp -Encoding UTF8
    try {
        $r = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/issues/$number" `
            -Method PATCH -Headers $headers -InFile $tmp -ContentType "application/json"
        Write-Host "UPDATED #${number}: $($r.title)"
    } catch {
        Write-Host "FAIL #${number}: $_"
    }
    Remove-Item $tmp -Force
    Start-Sleep -Seconds 2
}

Update-Issue 116 "**Type:** UIUX`n`n## Context`nUsers can only place one bet at a time, requiring multiple wallet approvals. This creates friction especially on mobile.`n`n## Guidelines`n- Slide-up drawer animating from bottom on mobile, side panel on desktop`n- Queue up to 5 bets, bundle into single Freighter transaction`n- Global drawer state via Redux or Context`n- Bet summary per queued item with remove option`n- Key requirement: Slide-up Drawer / Batching Logic`n`n---`n## Definition of Done`n- The drawer **animates correctly on both mobile and desktop** with no jank or layout shift on open/close`n- **Batch submission works end-to-end on Stellar testnet** and all queued bets land in a single transaction hash`n- **Removing a bet from the queue updates the summary instantly** without re-opening the drawer`n- Unit tests cover queue add, queue remove, batch submit, drawer toggle at **>90% coverage**`n- **Every function in the batching logic has an inline comment** explaining what it does and why`n- UI uses **only approved color tokens** (no hardcoded hex values) and respects the 4px spacing grid`n- README updated with a usage example showing how to open the drawer and submit a batch"

Update-Issue 117 "**Type:** UIUX`n`n## Context`nTraders need to quickly assess where liquidity is concentrated. A heatmap overlay gives instant depth perception without reading raw numbers.`n`n## Guidelines`n- CSS div overlays with opacity tied to pool size from the API`n- Blue for YES-side, orange for NO-side depth`n- Updates when pool data refreshes`n- Background layer behind order book rows`n- Key requirement: CSS Depth Overlays / Transparency`n`n---`n## Definition of Done`n- **Heatmap opacity values are mathematically tied to pool size** not hardcoded or approximated`n- **Color scale is visually distinguishable** between YES (blue) and NO (orange) at all opacity levels`n- **Overlay re-renders within 500ms** of a pool data refresh without flickering or full DOM repaint`n- Unit tests cover the **depth-to-opacity mapping function** with at least 5 boundary cases at **>90% coverage**`n- **Inline comments explain the opacity formula** and why the specific CSS layering order was chosen`n- Heatmap does **not obscure order book text** — z-index and pointer-events are correctly set`n- README documents the **API response shape** the heatmap expects (field names, units)"

Update-Issue 118 "**Type:** UIUX`n`n## Context`nGamification drives engagement. Badges create a status system that encourages long-term participation through visual recognition.`n`n## Guidelines`n- 4 SVG tiers: Bronze, Silver, Gold, Diamond`n- Award based on accuracy and markets participated`n- CSS box-shadow glow on hover per tier`n- Show on profile and leaderboard`n- Thresholds: Bronze >10, Silver >50+55%, Gold >100+65%, Diamond >200+75%`n- Key requirement: SVG Assets / Glow Micro-interactions`n`n---`n## Definition of Done`n- **All 4 SVG badge files are optimized** and render cleanly at both 24px and 64px`n- **Each tier has a visually distinct glow color**: Bronze amber, Silver gray-blue, Gold yellow, Diamond cyan`n- **Hover glow animation works in Chrome, Firefox, and Safari** — tested and confirmed on all three`n- **Award logic is a pure function** — given accuracy % and market count it returns the correct tier deterministically`n- Unit tests cover **all tier boundary conditions** (e.g. exactly 50 markets + 55% = Silver not Bronze) at **>90% coverage**`n- **Inline comments on the award function** explain each threshold and the reasoning behind it`n- README documents **how to add a new badge tier** without breaking existing logic"

Update-Issue 119 "**Type:** UIUX`n`n## Context`nSeeing other users actively betting builds trust and FOMO, two key drivers of prediction market engagement.`n`n## Guidelines`n- Scrolling ticker: 'User G***3 staked 50 XLM on YES'`n- Framer Motion entry/exit animations`n- WebSocket or 10s polling feed`n- Anonymize wallets (first 4 + last 3 chars)`n- Pause on hover`n- Key requirement: Framer Motion / Real-time Feed`n`n---`n## Definition of Done`n- **Ticker entries animate in and out without causing layout shift** — surrounding content does not move when a new entry appears`n- **Wallet anonymization is applied consistently** — no full addresses ever appear in the ticker under any condition`n- **Pause-on-hover works on both mouse and touch** — verified on mobile`n- **Feed reconnects automatically** if WebSocket drops or polling fails — no silent stale state`n- Unit tests cover anonymization function, entry queue management, pause/resume logic at **>90% coverage**`n- **Framer Motion variants are documented inline** explaining enter, center, and exit animation states`n- README documents the **backend endpoint or WebSocket event schema** the ticker consumes"

Update-Issue 120 "**Type:** UIUX`n`n## Context`nNew users unfamiliar with prediction markets or Stellar wallets need guided onboarding. Drop-off at wallet connection is high without it.`n`n## Guidelines`n- 4 steps: Connect Wallet, How Markets Work, Place First Bet, Understanding Payouts`n- Progress stepper at top of each step`n- Skip option to dashboard`n- Persist completion in localStorage`n- Key requirement: 4-step Progress Stepper / Logic`n`n---`n## Definition of Done`n- **All 4 steps render the correct content** — no placeholder text, no broken illustrations`n- **Progress stepper accurately reflects the current step** — step 2 shows 2/4 not 1/4 or 3/4`n- **Skip lands on the dashboard** and does not trigger any step logic or localStorage writes`n- **Completion state persists across hard refresh** — wizard does not re-appear after being completed`n- **Wizard does not appear for returning users** — localStorage check happens before any render`n- Unit tests cover step navigation, skip logic, localStorage read/write/clear at **>90% coverage**`n- **Each step component has inline comments** explaining what the user is being taught and why that order matters`n- README documents **how to reset the onboarding state** for QA testing"

Update-Issue 121 "**Type:** UIUX`n`n## Context`nUsers want to understand potential returns before committing funds. A simulator removes uncertainty and encourages larger, more confident stakes.`n`n## Guidelines`n- Collapsible simulator panel on market detail page`n- Input: stake amount via slider or text field`n- Output: projected payout/loss based on current pool odds`n- Recharts bar or line chart`n- Real-time update as user adjusts input`n- Key requirement: P&L Projections / Portfolio Charts`n`n---`n## Definition of Done`n- **P&L calculation matches the actual contract payout formula** — not an approximation, verified against testnet results`n- **Chart updates with zero perceptible lag** as the user moves the slider — debounced at 100ms max`n- **Implied probability is displayed as a percentage** and updates in sync with the chart`n- **Simulator works correctly at edge cases**: 0 XLM input, 100% pool ownership, single-outcome markets`n- Unit tests cover the **full P&L formula** including fee deduction and pool share math at **>90% coverage**`n- **Inline comments explain every step of the calculation** — pool share, fee, net payout`n- README documents **the exact formula used** so contributors can verify correctness independently"

Update-Issue 122 "**Type:** UIUX`n`n## Context`nIn fast-moving markets, users need an immediate visual signal when odds are shifting rapidly. A pulse animation draws attention without requiring constant number-watching.`n`n## Guidelines`n- Pulse animation when odds change >5% within 60 seconds`n- CSS @keyframes border or background glow`n- Green for rising YES odds, red for falling`n- Configurable threshold constant`n- 3 cycles then stops`n- Key requirement: CSS @keyframes / Color Logic`n`n---`n## Definition of Done`n- **Animation triggers at exactly the configured threshold** — tested at 4.9% (no trigger) and 5.1% (triggers)`n- **Green and red pulse colors meet contrast requirements** against the dark card background`n- **Animation runs exactly 3 cycles and stops** — does not loop, does not leave residual glow`n- **Threshold constant is defined in a single config file** — changing it in one place affects all cards`n- **Animation does not cause reflow or repaint of card content** — only the border/shadow animates`n- Unit tests cover threshold detection logic and color selection function at **>90% coverage**`n- **Inline comments on the @keyframes block** explain each animation phase and the timing rationale`n- README documents **where to find and change the threshold constant**"

Update-Issue 123 "**Type:** UIUX`n`n## Context`nIn markets with few large stakers, users want to see how the pool is distributed. A fractional ownership chart adds transparency and social context.`n`n## Guidelines`n- Recharts pie chart on market detail page`n- Each slice = one bettor's pool share`n- Tooltip: abbreviated wallet + exact stake`n- Live updates as new bets come in`n- Wallets <1% grouped into Others slice`n- Key requirement: Recharts / Fractional Ownership`n`n---`n## Definition of Done`n- **All slice percentages sum to exactly 100%** — no floating point drift, verified with BigInt math`n- **Others slice correctly groups all wallets below 1%** — tested with 50+ wallets where most are small`n- **Tooltip shows abbreviated address (first 6 + last 4)** and the exact XLM amount — never the full address`n- **Chart re-renders within 300ms** of a new bet being placed without full page refresh`n- **Chart is readable at mobile screen widths** — slices are not too thin to tap, tooltip is not clipped`n- Unit tests cover share calculation, Others grouping logic, address abbreviation at **>90% coverage**`n- **Inline comments explain the grouping threshold** and why 1% was chosen as the cutoff`n- README documents **the data structure the chart expects** from the API"

Update-Issue 124 "**Type:** UIUX`n`n## Context`nUsers need a way to discover new markets relevant to their interests. Generic lists don't drive engagement — personalized visually rich cards do.`n`n## Guidelines`n- SVG category illustrations: Sports, Crypto, Finance, Politics, Weather`n- Suggestion logic based on past activity or trending volume`n- Hover lift effect (CSS transform + box-shadow)`n- Show end date, pool size, category tag`n- Trending markets show Hot badge`n- Key requirement: SVG Illustrations / Suggestion Logic`n`n---`n## Definition of Done`n- **All 5 category SVGs render correctly** at card size (320px wide) and are visually distinct from each other`n- **Suggestion logic returns different results for different users** — a Sports bettor sees Sports markets first`n- **Hot badge only appears on markets in the top 10% by 24h volume** — threshold is configurable`n- **Hover lift effect works on desktop and does not trigger on mobile scroll** — touch vs mouse events handled separately`n- **Card shows correct end date, pool size, and category** — no stale data, no missing fields`n- Unit tests cover suggestion ranking algorithm and Hot badge threshold logic at **>90% coverage**`n- **Inline comments on the ranking function** explain the scoring formula (recency + volume weighting)`n- README documents **how to add a new category** including where to add the SVG and update the filter"

Update-Issue 125 "**Type:** UIUX`n`n## Context`nUsers miss critical events like market resolution and payouts because there is no in-app alert system. A notification inbox keeps users informed and drives them back to claim winnings.`n`n## Guidelines`n- Notification dropdown from navbar`n- Types: Market Resolved, Payout Available, Market Ending in 1 Hour`n- z-index 1100 above all modals`n- Read/unread state with blue dot`n- Clear All button`n- Persist in localStorage or backend`n- Key requirement: Inbox Logic / Z-index 1100`n`n---`n## Definition of Done`n- **All 3 notification types render with the correct icon, title, and body text** — no generic fallback messages`n- **z-index 1100 is verified on every page** including pages with modals, drawers, and tooltips — dropdown is never obscured`n- **Unread blue dot appears only on genuinely unread notifications** — clicking a notification marks it read immediately`n- **Clear All removes all notifications from state and localStorage** — they do not reappear on refresh`n- **Notification count badge on the navbar icon is accurate** — shows 0 when all are read`n- Unit tests cover notification creation, read/unread toggle, clear all, persistence at **>90% coverage**`n- **Inline comments explain the z-index strategy** and why 1100 was chosen relative to other layered elements`n- README documents **how to add a new notification type** in the future"

Write-Host "=== UIUX updated (116-125) ==="
